---
title: "Apoie"
type: "apoie"
output: html_document
toc: true
---

<div style=text-align:center>Atualmente é possível apoiar o trabalho que desenvolvemos na ABJ de 3 formas.</div>

<header class="section-header">
## Associação
</header>

Ao se associar, você se torna parte de uma comunidade comprometida em promover a jurimetria e impulsionar avanços significativos no campo do Direito. Como membro, você terá acesso exclusivo ao Portal da ABJ com recursos e informações atualizadas, terá descontos em cursos e eventos e poderá se conectar a profissionais e especialistas de renome em uma rede de colaboração sem igual. Além disso, você estará contribuindo diretamente para o fortalecimento da jurimetria e ajudando-nos a impulsioná-la para uma sociedade mais justa e equitativa. Junte-se a nós hoje e faça a diferença!

**Público-alvo**: Estudantes, profissionais com interesse em desenvolver pesquisas que utilizam jurimetria.

Diferente de uma consultoria, a ABJ oferece orientação, bases de dados e troca de informações e experiências.
Veja os principais benefícios para quem faz parte da ABJ. Todos os benefícios podem ser acessados a qualquer momento na nossa área exclusiva.

Veja os principais benefícios para quem faz parte da ABJ. Todos os benefícios podem ser acessados a qualquer momento na nossa [**área exclusiva**](https://abjur.shinyapps.io/associados).


<div>
<div id="contact">

<!--linha 1-->
<div class="row contact-info">

<div class="col-md-4"><div>
<i class="fas fa-comment-dots"></i>
<h3>Atendimento e auxílio</h3>
<p>Atendimento consultivo para discutir os caminhos na elaboração de pesquisas e auxílio em levantamentos simples.</p>
</div></div>

<div class="col-md-4"><div>
<i class="fas fa-coffee"></i>
<h3>Café</h3>
<p>Acesso exclusivo ao café jurimétrico, nosso evento online que traz novidades sobre o universo da jurimetria.</p>
</div></div>

<div class="col-md-4"><div>
<i class="fas fa-chart-area"></i>   
<h3>Portal da ABJ</h3>
<p>Acesso ao Portal da ABJ, dashboard interativo baseado nos dados da consulta de Jurisprudência do TJSP.</p>
</div></div>

</div>

<br/>

<!--linha 2-->
<div class="row contact-info">

<div class="col-md-4"><div>
<i class="fas fa-flask"></i>
<h3>Blog</h3>
<p>Possibilidade de publicar textos no <a href="https://lab.abj.org.br" target="_blank">Laboratório de Jurimetria</a>, o blog acadêmico da ABJ.</p>
</div></div>

<div class="col-md-4"><div>
<i class="fas fa-percent"></i>
<h3>Descontos</h3>
<p>Descontos em cursos e eventos parceiros da ABJ.</p>
</div></div>

<a href="https://docs.google.com/forms/d/e/1FAIpQLSdymc2juV7SKG7_ZBKPGn7lmFDvno-Nd4dxb9NVpenP8Siovw/viewform"><div class="col-md-4" style="background: #f8f8ff" target="_blank"><div>
<i class="fas fa-question"></i>
<h3>Sugestões?</h3>
<p><a href="https://docs.google.com/forms/d/e/1FAIpQLSdymc2juV7SKG7_ZBKPGn7lmFDvno-Nd4dxb9NVpenP8Siovw/viewform" target="_blank"><strong>Preencha este formulário</strong></a> para nos ajudar a melhorar nossos benefícios!</p></a>

</div>

<br/>
<!--linha 3-->

</div>

<!--fim da linha-->
</div>

<!--botoes de associados --->

<div class="row associe-se">
<div class="col-md-6">
<a href="https://app.associatec.com.br/AreaAssociados/Abj?returnUrl=https://app.associatec.com.br/AreaAssociados/MinhaConta/CadastroAssociadoPF?idTipoAssociado=2380" target="_blank"><div>
<i class="fas fa-graduation-cap"></i>
<h4>Estudante</h3>
<h4>R\$ 525,00 ou 6x R\$ 87,50 </h3>
<p>Indicado para estudantes e professores</p>
</div></a></div>

<div class="col-md-6">
<a href="https://app.associatec.com.br/AreaAssociados/Abj?returnUrl=https://app.associatec.com.br/AreaAssociados/MinhaConta/CadastroAssociadoPF?idTipoAssociado=2379" target="_blank"><div>
<i class="fas fa-user-tie"></i>
<h4>Profissional</h4>
<h4>R\$ 1.050,00 ou 6x R\$ 175,00 </h4>
<p>Profissionais interessados na jurimetria</p>
</div></a></div> 

</div></div>

<div><header class="section-header">
## Apoio institucional
</header>

Seja um parceiro estratégico e fortaleça sua marca enquanto impulsiona a jurimetria com a ABJ.

Ao oferecer apoio institucional, sua empresa, escritório de advocacia ou lawtech demonstrará liderança e comprometimento com o progresso do Direito. Como parceiros, podemos colaborar para desenvolver iniciativas personalizadas e, além disso, oferecer acesso aos benefícios de associação, como os descontos em cursos de capacitação e eventos, networking com os principais profissionais do setor e oportunidades de visibilidade em nossos eventos. Junte-se a nós e faça parte da vanguarda da transformação jurídica, destacando-se como um líder inovador e impulsionando o futuro da justiça!
</div>

<div class="row associe-se">
<div class="col-md-6">
<a href="https://app.associatec.com.br/AreaAssociados/Abj?returnUrl=https://app.associatec.com.br/AreaAssociados/MinhaConta/CadastroAssociadoPJ?idTipoAssociado=2382" target="_blank"><div>
<i class="fas fa-home"></i>
<h4>Legaltech / Lawtech</h4>
<h4>R\$ 3.360,00 ou 6x R\$ 560,0 </h4>
<p>Destinado a startups que desejam empreender no ramo da jurimetria</p>
</div></a>
</div>
<div class="col-md-6">
<a href="https://app.associatec.com.br/AreaAssociados/Abj?returnUrl=https://app.associatec.com.br/AreaAssociados/MinhaConta/CadastroAssociadoPJ?idTipoAssociado=2381" target="_blank"><div>
<i class="fas fa-building"></i>
<h4>Empresa ou escritório</h4>
<h4>R\$ 6.720,00 ou 6x R\$ 1.120,00</h4>
<p>Destinado a empresas públicas ou privadas e escritórios de advocacia interessados em apoiar a ABJ</p>
</div></a>
</div></div>

<div><header class="section-header">
## Patrocínios
</header>

O patrocínio de estudos jurimétricos é uma forma poderosa de demonstrar o compromisso da sua empresa ou escritório em transformar a sociedade através do Direito baseado em dados, e sua dedicação em impulsionar a pesquisa e o desenvolvimento de soluções. 

Ao patrocinar estudos em jurimetria, você estará direcionando recursos valiosos para impulsionar a investigação acadêmica, a análise de dados e a aplicação de técnicas avançadas para aprimorar o conhecimento jurídico. Seja uma força motriz por trás da mudança ao apoiar nossos estudos, fortalecendo a base de evidências e capacitando profissionais do Direito a tomar decisões embasadas. 

Junte-se a nós nessa jornada transformadora! Envie um e-mail para [contato@abj.org.br](mailto:contato@abj.org.br).

<div><header class="section-header">
# Empresas que nos apoiam
</header>

Impulsionam e contribuem para o avanço da Jurimetria no Brasil

<div class="row" style="align:center;">

```{r, echo=FALSE, message=FALSE, warning=FALSE, results="html", eval=TRUE}

obsutils::autenticar_gsheets()
id_pj <- googledrive::as_id("1QpgnN1QaJlZH6zgqviLb0zNCdedW7lBS57EZS11uspg")
da_pj <- googlesheets4::read_sheet(id_pj) |>
  dplyr::filter(publicar == "s")

montar_div <- function(dados) {
  if (dados$inverter == "s") {
    if (dados$grayscale == "s") {
      st <- "-webkit-filter:grayscale(1) invert(1);filter:grayscale(1) invert(1);max-width: 80%;display:block;"
    } else {
      st <- "-webkit-filter:invert(1);filter:invert(1);max-width: 80%;display:block;margin-left: auto;margin-right: auto;"
    }
  } else {
    if (dados$grayscale == "s") {
      st <- "max-width:80%;display:block;-webkit-filter:grayscale(.5);filter:grayscale(.5);position:absolute;"
    } else {
      st <- "max-width:80%;display:block;margin-left: auto;margin-right:auto;position:absoute;"
    }
  }

  shiny::div(
    class = "col-md-4",
    shiny::a(
      shiny::div(
        shiny::img(src = dados$logo, style = st), 
        style = "display:flex;height:100%;width:100%;justify-content:center;align-items: center;"
      ),
      href = dados$site, target="_blank",
    ), 
    style = "padding-bottom:0px;background-color:#f8f8ff;margin:10px 0px 0px 0px;min-height:200px;"
  )
}


da_pj |> 
  dplyr::select(-modalidade) |> 
  dplyr::group_split(empresa) |> 
  purrr::map(montar_div) |> 
  shiny::tagList()
```

</div></div>

