---
title: "Contato"
type: "contato"
---

<!-- FAQ -->

<header class="section-header">
<h1 id="faq">Dúvidas Frequentes</h1>
</header>

Abaixo você encontra as respostas para dúvidas frequentes que recebemos aqui na ABJ. Caso tenha alguma dúvida que não esteja por aqui, [entre em contato](/contato) com nossa equipe.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
obsutils::autenticar_gsheets()
id <- googledrive::as_id("1K9i4R2jZoYu03BMcrsGx0tHPBmVQbF4Lj9YwgIs1bh8")
da <- googlesheets4::read_sheet(id)

criar_tag <- function(.x, .y) {
  button <- .x |>
    shiny::tags$button(class = "accordion") |>
    shiny::p()
  text <- .y |>
    markdown::markdownToHTML(text = _, fragment.only = TRUE) |>
    stringr::str_remove("^<p>") |>
    stringr::str_remove("</p>$") |>
    shiny::HTML() |>
    shiny::p() |>
    shiny::div(class = "panel")
  shiny::tagList(button, text)
}
a <- with(da, purrr::map2(pergunta, resposta, criar_tag))
```

<h2>Pessoas associadas</h2>


```{r, results='html', echo=FALSE}
shiny::tagList(a[which(da$tema == "Pessoas associadas")])
```

<h2>Pessoas não associadas</h2>

```{r, results='html', echo=FALSE}
shiny::tagList(a[which(da$tema == "Pessoas não associadas")])
```
