---
title: "Dúvidas Frequentes"
type: "faq"
output: md_document
toc: true
always_allow_html: true
---

<!-- FAQ -->

Abaixo você encontra as respostas para dúvidas frequentes que recebemos aqui na ABJ. Caso tenha alguma dúvida que não esteja por aqui, [entre em contato](/contato) com nossa equipe.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
obsutils::autenticar_gsheets()
id <- googledrive::as_id("1K9i4R2jZoYu03BMcrsGx0tHPBmVQbF4Lj9YwgIs1bh8")
da <- googlesheets4::read_sheet(id)

md_html <- function(txt) {
  txt |>
    markdown::markdownToHTML(fragment.only = TRUE) |>
    stringr::str_remove("^<p>") |>
    stringr::str_remove("</p>$")
}
da <- dplyr::mutate(da, resposta = purrr::map_vec(resposta, md_html))

criar_tag <- function(.x, .y) {
  shiny::tagList(
    shiny::p(shiny::tags$button(class = "accordion", .x)),
    shiny::div(
      class = "panel", 
      shiny::p(shiny::HTML(.y))
    )
  )
}
a <- with(da, purrr::map2(pergunta, resposta, criar_tag))
```

<h2>Geral</h2>


```{r, results='html', echo=FALSE}
shiny::tagList(a[which(da$tema == "Geral")])
```

<h2>Pessoas associadas</h2>

```{r, results='html', echo=FALSE}
shiny::tagList(a[which(da$tema == "Pessoas associadas")])
```
