---
title: "Observatório da Insolvência - Recuperações Judiciais no Mato Grosso"
summary: "O foco deste projeto é levantar e analisar dados a respeito das empresas em crise que se dirigem ao Poder Judiciário para viabilizar meios de recuperação ou, em último caso, para serem liquidadas."
type: "observatorios"
img: "img/pesquisas/obsrjmt.png"
toc: true
output: html_document
always_allow_html: true
draft: false
---

O foco deste projeto é levantar e analisar dados a respeito das empresas em crise que se dirigem ao Poder Judiciário para viabilizar meios de recuperação ou, em último caso, para serem liquidadas.


<h2>Objetivos</h2>
<p>O trabalho teve como objetivos auxiliar na elaboração e alteração de leis sobre o tema e compreender empiricamente o processo de Recuperação Judicial, incluindo:</p>
<ul>
<li>O que influencia no deferimento e quanto tempo ele leva?</li>
<li>O que acontece entre deferimento e aprovação do plano?</li>
<li>Quais são as características gerais dos planos de recuperação aprovados?</li>
</ul>
<h2>Metodologia</h2>
O trabalho foi pioneiro no que tange a análise sobre processos de recuperação judicial envolvendo produtores rurais. Foram analisadas todas as recuperações distribuídas entre 01/01/2020 e 31/12/2024 em Mato Grosso. Os processos foram analisados manualmente por pesquisadores.

<p>Neste projeto, estudamos e acompanhamos 196 Recuperações judiciais no estado do Mato Grosso, analisando dados sobre deferimento e planos de recuperação homologados.</p>

<a href="https://drive.google.com/file/d/1aABXMhTkEkgJbEPCtD9ogmtuJn9YLxJu/view?usp=sharing">[Relatório]</a>

<h2>Patrocinadores</h2>
<p>O Observatório da Insolvência não seria possível sem nossos patrocinadores. Abaixo listamos os patrocinadores desta fase do projeto.</p>
</div>
